/// Additional analyzer diagnostics used by `flutter_skill_lints`.
///
/// These rules, fixes, and assists preserve their diagnostic IDs so existing
/// analyzer configuration can keep using the same rule names through the
/// `flutter_skill_lints` plugin.
library;

import 'package:analysis_server_plugin/plugin.dart';
import 'package:analysis_server_plugin/registry.dart';
import 'package:flutter_skill_lints/src/additional_lints/dcm_expansion_lints.dart';
// Assists
import 'package:flutter_skill_lints/src/additional_lints/assists/convert_iterable_map_to_collection_for.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/add_suffix_fix.dart';
// Fixes
import 'package:flutter_skill_lints/src/additional_lints/fixes/always_remove_listener_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_border_all_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_cascade_after_if_null_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_commented_out_code_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_duplicate_cascades_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_expanded_as_spacer_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_generics_shadowing_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_incomplete_copy_with_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_incorrect_image_opacity_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_map_keys_contains_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_mounted_check_in_finally_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_notifier_constructors_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_only_rethrow_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_ref_read_inside_build_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_single_field_destructuring_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_state_constructors_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_throw_in_catch_block_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_unnecessary_consumer_widgets_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_unnecessary_gesture_detector_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_unnecessary_hook_widgets_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_unnecessary_overrides_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_unnecessary_overrides_in_state_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_unnecessary_setstate_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_unnecessary_stateful_widgets_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/avoid_wrapping_in_padding_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/change_widget_name_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/dispose_fields_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/dispose_provided_instances_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_abstract_final_static_class_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_any_or_every_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_async_callback_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_center_over_align_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_class_destructuring_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_compute_over_isolate_run_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_const_border_radius_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_constrained_box_over_container_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_container_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_correct_edge_insets_constructor_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_enums_by_name_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_expect_later_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_explicit_function_type_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_for_loop_in_children_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_iterable_of_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_padding_over_container_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_return_await_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_simpler_patterns_null_check_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_single_setstate_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_sized_box_square_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_text_rich_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_use_callback_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_use_prefix_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_void_callback_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/prefer_wildcard_pattern_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/proper_super_calls_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/use_closest_build_context_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/use_dedicated_media_query_methods_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/use_existing_destructuring_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/use_existing_variable_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/use_ref_and_state_synchronously_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/use_ref_read_synchronously_fix.dart';
import 'package:flutter_skill_lints/src/additional_lints/fixes/use_sliver_prefix_fix.dart';
// Rules
import 'package:flutter_skill_lints/src/additional_lints/rules/always_remove_listener.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/always_pass_global_key.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_accessing_collections_by_constant_index.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_adjacent_strings.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_async_callback_in_fake_async.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_async_call_in_sync_function.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_assignments_as_conditions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_assigning_to_static_field.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_assigning_notifiers.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_banned_annotations.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_banned_exports.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_banned_file_names.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_banned_imports.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_border_all.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_bottom_type_in_patterns.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_bottom_type_in_records.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_cascade_after_if_null.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_calling_notifier_members_inside_build.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_collection_equality_checks.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_collection_mutating_methods.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_collection_methods_with_unrelated_types.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_commented_out_code.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_conditional_hooks.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_constant_conditions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_constant_switches.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_contradictory_expressions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_complex_conditions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_disposing_late_fields.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_cascades.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_collection_elements.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_test_assertions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_double_slash_imports.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_empty_setstate.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_empty_spread.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_empty_test_groups.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_enum_values_by_index.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_extensions_on_records.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_expanded_as_spacer.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_flexible_outside_flex.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_flutter_skill_lint_suppression.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_function_type_in_records.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_future_ignore.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_future_tostring.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_futureor_return_type.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_generics_shadowing.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_global_state.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_hardcoded_strings.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_hooks_outside_build.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_if_with_many_branches.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_implementation_in_mocks.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_implicitly_nullable_extension_types.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_incomplete_copy_with.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_incorrect_image_opacity.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_inline_error_codes.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_inherited_widget_in_initstate.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_inverted_boolean_checks.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_labels.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_late_context.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_late_keyword.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_local_functions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_local_contract_key_constants.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_long_files.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_long_functions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_long_parameter_list.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_long_records.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_magic_literals.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_map_keys_contains.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_missing_completer_stack_trace.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_missing_controller.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_missing_image_alt.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_missing_interpolation.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_missing_test_files.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_missed_calls.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_misused_test_matchers.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_misused_hooks.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_mixing_named_and_positional_fields.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_mounted_check_in_finally.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_mounted_in_setstate.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_multi_assignment.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_mutating_parameters.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_negations_in_equality_checks.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nested_conditional_expressions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nested_futures.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nested_records.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nested_streams_and_futures.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_non_empty_constructor_bodies.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nullable_async_or_collection_return_type.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nullable_async_value_pattern.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nullable_interpolation.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nullable_tostring.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_notifier_constructors.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_only_rethrow.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_passing_async_when_sync_expected.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_positional_record_fields.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_public_late_final_without_initializer.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_public_notifier_properties.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_recursive_widget_calls.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_ref_inside_state_dispose.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_ref_read_inside_build.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_ref_watch_outside_build.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_referencing_discarded_variables.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_repeated_property_aliases.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_returning_widgets.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_shrink_wrap_in_lists.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_single_child_in_multi_child_widgets.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_single_field_destructuring.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_state_constructors.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_stateless_widget_initialized_fields.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_then_return_with_future.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_throw_in_catch_block.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_throw_objects_without_tostring.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_top_level_members_in_tests.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_type_casts.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unassigned_stream_subscriptions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_uncaught_future_errors.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_consumer_widgets.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_digit_separators.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_else_after_control_flow.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_enum_arguments.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_gesture_detector.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_hook_widgets.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_nullable_return_type.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_overrides.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_overrides_in_state.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_safe_area.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_setstate.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_stateful_widgets.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_type_assertions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_undisposed_instances.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_wrapping_in_padding.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/check_for_equals_in_render_object_setters.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/dispose_fields.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/dispose_provided_instances.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/incorrect_firebase_event_name.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/incorrect_firebase_parameter_name.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/keep_state_below_its_widget.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/match_lib_folder_structure.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/missing_test_assertion.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/move_records_to_typedefs.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/no_equal_then_else.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/pass_mock_object.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/pass_existing_future_to_future_builder.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/pass_existing_stream_to_stream_builder.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_abstract_final_static_class.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_align_over_container.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_any_or_every.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_action_button_tooltip.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_async_await.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_async_callback.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_center_over_align.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_class_destructuring.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_compute_over_isolate_run.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_const_border_radius.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_constrained_box_over_container.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_container.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_caret_version_syntax.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_correct_edge_insets_constructor.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_correct_any_matcher.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_correct_json_casts.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_correct_test_file_name.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_date_format.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_define_hero_tag.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_enums_by_name.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_expect_later.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_explicit_function_type.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_for_loop_in_children.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_immutable_provider_arguments.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_intl_name.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_iterable_of.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_match_file_name.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_padding_over_container.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_private_extension_type_field.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_return_await.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_simpler_patterns_null_check.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_single_setstate.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_single_widget_per_file.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_sized_box_square.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_spacing.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_test_matchers.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_text_rich.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_transform_over_container.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_unique_test_names.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_use_callback.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_use_prefix.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_using_list_view.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_void_callback.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_widget_private_members.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_wildcard_pattern.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/proper_super_calls.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/pubspec_ordering.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/require_atomic_async_updates.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/resolve_platform_specific_implementation_before_use.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_closest_build_context.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_context_is_current_modal_route.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_dedicated_media_query_methods.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_local_notifications_exact_alarm_permission_api.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_on_reorder_item_index_semantics.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_existing_destructuring.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_existing_variable.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_notifier_suffix.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_ref_and_state_synchronously.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_ref_read_synchronously.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_setstate_synchronously.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_sliver_prefix.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/use_then_answer.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_accessing_other_classes_private_members.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_banned_names.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_banned_types.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_bitwise_operators_with_booleans.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_collapsible_if.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_conditions_with_boolean_literals.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_constant_assert_conditions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_continue.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_default_tostring.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_constant_values.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_exports.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_map_keys.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_equal_expressions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_identical_exception_handling_blocks.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_late_final_reassignment.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nested_try_statements.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_one_field_records.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_positional_record_field_access.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_recursive_tostring.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_redundant_async.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_redundant_else.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_redundant_positional_field_name.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_returning_void.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_self_assignment.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_self_compare.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_stream_tostring.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_throw.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unassigned_fields.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unassigned_late_fields.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_futures.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_if.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/no_boolean_literal_compare.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/no_empty_block.dart';

/// Additional Dart and Flutter diagnostics for the Flutter skill profile.
class AdditionalLintsPlugin extends Plugin {
  @override
  String get name => 'Flutter Skill Additional Lints';

  @override
  void register(PluginRegistry registry) {
    // Register warning rules (enabled by default)
    registry.registerWarningRule(AlwaysRemoveListener());
    registry.registerWarningRule(AlwaysPassGlobalKey());
    registry.registerWarningRule(AvoidAdjacentStrings());
    registry.registerWarningRule(AvoidAsyncCallbackInFakeAsync());
    registry.registerWarningRule(AvoidAsyncCallInSyncFunction());
    registry.registerWarningRule(AvoidAssignmentsAsConditions());
    registry.registerWarningRule(AvoidAssigningToStaticField());
    registry.registerWarningRule(AvoidAssigningNotifiers());
    registry.registerWarningRule(AvoidBannedAnnotations());
    registry.registerWarningRule(AvoidBannedExports());
    registry.registerWarningRule(AvoidBannedFileNames());
    registry.registerWarningRule(AvoidBannedImports());
    registry.registerWarningRule(AvoidBottomTypeInPatterns());
    registry.registerWarningRule(AvoidBottomTypeInRecords());
    registry.registerWarningRule(AvoidCascadeAfterIfNull());
    registry.registerWarningRule(AvoidCallingNotifierMembersInsideBuild());
    registry.registerWarningRule(AvoidCommentedOutCode());
    registry.registerWarningRule(AvoidComplexConditions());
    registry.registerWarningRule(AvoidDisposingLateFields());
    registry.registerWarningRule(AvoidDuplicateCascades());
    registry.registerWarningRule(AvoidDuplicateCollectionElements());
    registry.registerWarningRule(AvoidDuplicateTestAssertions());
    registry.registerWarningRule(AvoidDoubleSlashImports());
    registry.registerWarningRule(AvoidEmptySetstate());
    registry.registerWarningRule(AvoidEmptySpread());
    registry.registerWarningRule(AvoidEmptyTestGroups());
    registry.registerWarningRule(AvoidEnumValuesByIndex());
    registry.registerWarningRule(AvoidExtensionsOnRecords());
    registry.registerWarningRule(AvoidConstantConditions());
    registry.registerWarningRule(AvoidConstantSwitches());
    registry.registerWarningRule(AvoidContradictoryExpressions());
    registry.registerWarningRule(AvoidAccessingCollectionsByConstantIndex());
    registry.registerWarningRule(AvoidFunctionTypeInRecords());
    registry.registerWarningRule(AvoidFutureIgnore());
    registry.registerWarningRule(AvoidFutureToString());
    registry.registerWarningRule(AvoidGenericsShadowing());
    registry.registerWarningRule(AvoidHooksOutsideBuild());
    registry.registerWarningRule(AvoidIfWithManyBranches());
    registry.registerWarningRule(AvoidImplementationInMocks());
    registry.registerWarningRule(AvoidImplicitlyNullableExtensionTypes());
    registry.registerWarningRule(AvoidInheritedWidgetInInitstate());
    registry.registerWarningRule(AvoidInvertedBooleanChecks());
    registry.registerWarningRule(AvoidLabels());
    registry.registerWarningRule(AvoidLateContext());
    registry.registerWarningRule(AvoidLateKeyword());
    registry.registerWarningRule(AvoidLocalFunctions());
    registry.registerWarningRule(AvoidLongFiles());
    registry.registerWarningRule(AvoidLongFunctions());
    registry.registerWarningRule(AvoidLongParameterList());
    registry.registerWarningRule(AvoidLongRecords());
    registry.registerWarningRule(AvoidMapKeysContains());
    registry.registerWarningRule(AvoidMissingCompleterStackTrace());
    registry.registerWarningRule(AvoidMissingController());
    registry.registerWarningRule(AvoidMissingImageAlt());
    registry.registerWarningRule(AvoidMissingInterpolation());
    registry.registerWarningRule(AvoidMissingTestFiles());
    registry.registerWarningRule(AvoidMissedCalls());
    registry.registerWarningRule(AvoidMisusedHooks());
    registry.registerWarningRule(AvoidMisusedTestMatchers());
    registry.registerWarningRule(AvoidMixingNamedAndPositionalFields());
    registry.registerWarningRule(AvoidMountedCheckInFinally());
    registry.registerWarningRule(AvoidOnlyRethrow());
    registry.registerWarningRule(AvoidMultiAssignment());
    registry.registerWarningRule(AvoidMutatingParameters());
    registry.registerWarningRule(AvoidNegationsInEqualityChecks());
    registry.registerWarningRule(AvoidNestedConditionalExpressions());
    registry.registerWarningRule(AvoidNestedFutures());
    registry.registerWarningRule(AvoidNestedRecords());
    registry.registerWarningRule(AvoidNestedStreamsAndFutures());
    registry.registerWarningRule(AvoidNonEmptyConstructorBodies());
    registry.registerWarningRule(AvoidFutureOrReturnType());
    registry.registerWarningRule(AvoidNullableAsyncOrCollectionReturnType());
    registry.registerWarningRule(AvoidNullableAsyncValuePattern());
    registry.registerWarningRule(AvoidNullableInterpolation());
    registry.registerWarningRule(AvoidNullableToString());
    registry.registerWarningRule(AvoidPassingAsyncWhenSyncExpected());
    registry.registerWarningRule(AvoidPublicLateFinalWithoutInitializer());
    registry.registerWarningRule(AvoidPublicNotifierProperties());
    registry.registerWarningRule(AvoidRecursiveWidgetCalls());
    registry.registerWarningRule(AvoidRefInsideStateDispose());
    registry.registerWarningRule(AvoidThrowInCatchBlock());
    registry.registerWarningRule(AvoidThrowObjectsWithoutToString());
    registry.registerWarningRule(AvoidUnassignedStreamSubscriptions());
    registry.registerWarningRule(AvoidUncaughtFutureErrors());
    registry.registerWarningRule(AvoidReferencingDiscardedVariables());
    registry.registerWarningRule(AvoidFlexibleOutsideFlex());
    registry.registerWarningRule(AvoidFlutterSkillLintSuppression());
    registry.registerWarningRule(AvoidIncompleteCopyWith());
    registry.registerWarningRule(AvoidIncorrectImageOpacity());
    registry.registerWarningRule(AvoidInlineErrorCodes());
    registry.registerWarningRule(AvoidLocalContractKeyConstants());
    registry.registerWarningRule(AvoidMagicLiterals());
    registry.registerWarningRule(AvoidUnnecessaryGestureDetector());
    registry.registerWarningRule(AvoidUnnecessaryOverrides());
    registry.registerWarningRule(AvoidUnnecessaryOverridesInState());
    registry.registerWarningRule(AvoidUnnecessarySetstate());
    registry.registerWarningRule(AvoidUnnecessaryStatefulWidgets());
    registry.registerWarningRule(AvoidMountedInSetstate());
    registry.registerWarningRule(AvoidCollectionEqualityChecks());
    registry.registerWarningRule(AvoidCollectionMutatingMethods());
    registry.registerWarningRule(DisposeFields());
    registry.registerWarningRule(DisposeProvidedInstances());
    registry.registerWarningRule(AvoidCollectionMethodsWithUnrelatedTypes());
    registry.registerWarningRule(PreferAbstractFinalStaticClass());
    registry.registerWarningRule(PreferCenterOverAlign());
    registry.registerWarningRule(PreferAlignOverContainer());
    registry.registerWarningRule(PreferExplicitFunctionType());
    registry.registerWarningRule(PreferPaddingOverContainer());
    registry.registerWarningRule(PreferReturnAwait());
    registry.registerWarningRule(PreferSimplerPatternsNullCheck());
    registry.registerWarningRule(PreferWildcardPattern());
    registry.registerWarningRule(PreferAnyOrEvery());
    registry.registerWarningRule(PreferEnumsByName());
    registry.registerWarningRule(PreferExpectLater());
    registry.registerWarningRule(PreferIterableOf());
    registry.registerWarningRule(AvoidSingleChildInMultiChildWidgets());
    registry.registerWarningRule(AvoidUnnecessaryHookWidgets());
    registry.registerWarningRule(AvoidUnnecessaryNullableReturnType());
    registry.registerWarningRule(AvoidConditionalHooks());
    registry.registerWarningRule(AvoidUnnecessaryConsumerWidgets());
    registry.registerWarningRule(AvoidUnnecessaryDigitSeparators());
    registry.registerWarningRule(AvoidUnnecessaryElseAfterControlFlow());
    registry.registerWarningRule(AvoidUnnecessaryEnumArguments());
    registry.registerWarningRule(AvoidUnnecessarySafeArea());
    registry.registerWarningRule(AvoidUnnecessaryTypeAssertions());
    registry.registerWarningRule(UseNotifierSuffix());
    registry.registerWarningRule(UseContextIsCurrentModalRoute());
    registry.registerWarningRule(UseDedicatedMediaQueryMethods());
    registry.registerWarningRule(PreferSingleWidgetPerFile());
    registry.registerWarningRule(PreferSpacing());
    registry.registerWarningRule(PreferTestMatchers());
    registry.registerWarningRule(ProperSuperCalls());
    registry.registerWarningRule(PreferClassDestructuring());
    registry.registerWarningRule(UseClosestBuildContext());
    registry.registerWarningRule(UseExistingDestructuring());
    registry.registerWarningRule(UseExistingVariable());
    registry.registerWarningRule(AvoidSingleFieldDestructuring());
    registry.registerWarningRule(AvoidBorderAll());
    registry.registerWarningRule(AvoidExpandedAsSpacer());
    registry.registerWarningRule(AvoidGlobalState());
    registry.registerWarningRule(AvoidHardcodedStrings());
    registry.registerWarningRule(AvoidReturningWidgets());
    registry.registerWarningRule(AvoidShrinkWrapInLists());
    registry.registerWarningRule(AvoidNotifierConstructors());
    registry.registerWarningRule(AvoidRefReadInsideBuild());
    registry.registerWarningRule(AvoidRefWatchOutsideBuild());
    registry.registerWarningRule(AvoidStateConstructors());
    registry.registerWarningRule(AvoidStatelessWidgetInitializedFields());
    registry.registerWarningRule(PreferAsyncCallback());
    registry.registerWarningRule(PreferComputeOverIsolateRun());
    registry.registerWarningRule(PreferConstBorderRadius());
    registry.registerWarningRule(AvoidWrappingInPadding());
    registry.registerWarningRule(CheckForEqualsInRenderObjectSetters());
    registry.registerWarningRule(PreferConstrainedBoxOverContainer());
    registry.registerWarningRule(PreferContainer());
    registry.registerWarningRule(PreferCorrectEdgeInsetsConstructor());
    registry.registerWarningRule(PreferForLoopInChildren());
    registry.registerWarningRule(PreferSingleSetstate());
    registry.registerWarningRule(PreferSizedBoxSquare());
    registry.registerWarningRule(PreferTextRich());
    registry.registerWarningRule(PreferTransformOverContainer());
    registry.registerWarningRule(PreferVoidCallback());
    registry.registerWarningRule(UseRefAndStateSynchronously());
    registry.registerWarningRule(UseRefReadSynchronously());
    registry.registerWarningRule(ResolvePlatformSpecificImplementationBeforeUse());
    registry.registerWarningRule(UseLocalNotificationsExactAlarmPermissionApi());
    registry.registerWarningRule(UseOnReorderItemIndexSemantics());
    registry.registerWarningRule(PreferUseCallback());
    registry.registerWarningRule(PreferUsePrefix());
    registry.registerWarningRule(PreferUsingListView());
    registry.registerWarningRule(UseSliverPrefix());
    registry.registerWarningRule(NoBooleanLiteralCompare());
    registry.registerWarningRule(NoEmptyBlock());
    registry.registerWarningRule(NoEqualThenElse());
    registry.registerWarningRule(AvoidUndisposedInstances());
    registry.registerWarningRule(AvoidThenReturnWithFuture());
    registry.registerWarningRule(AvoidTopLevelMembersInTests());
    registry.registerWarningRule(AvoidTypeCasts());
    registry.registerWarningRule(IncorrectFirebaseEventName());
    registry.registerWarningRule(IncorrectFirebaseParameterName());
    registry.registerWarningRule(MissingTestAssertion());
    registry.registerWarningRule(MoveRecordsToTypedefs());
    registry.registerWarningRule(PassExistingFutureToFutureBuilder());
    registry.registerWarningRule(PassExistingStreamToStreamBuilder());
    registry.registerWarningRule(PassMockObject());
    registry.registerWarningRule(PreferActionButtonTooltip());
    registry.registerWarningRule(PreferAsyncAwait());
    registry.registerWarningRule(PreferCaretVersionSyntax());
    registry.registerWarningRule(PreferCorrectAnyMatcher());
    registry.registerWarningRule(PreferCorrectJsonCasts());
    registry.registerWarningRule(PreferCorrectTestFileName());
    registry.registerWarningRule(PreferDateFormat());
    registry.registerWarningRule(PreferDefineHeroTag());
    registry.registerWarningRule(PreferImmutableProviderArguments());
    registry.registerWarningRule(PreferIntlName());
    registry.registerWarningRule(PreferMatchFileName());
    registry.registerWarningRule(PreferPrivateExtensionTypeField());
    registry.registerWarningRule(PreferUniqueTestNames());
    registry.registerWarningRule(PreferWidgetPrivateMembers());
    registry.registerWarningRule(PubspecOrdering());
    registry.registerWarningRule(RequireAtomicAsyncUpdates());
    registry.registerWarningRule(KeepStateBelowItsWidget());
    registry.registerWarningRule(MatchLibFolderStructure());
    registerDcmExpansionLints(registry);
    registry.registerWarningRule(AvoidAccessingOtherClassesPrivateMembers());
    registry.registerWarningRule(AvoidBannedNames());
    registry.registerWarningRule(AvoidBannedTypes());
    registry.registerWarningRule(AvoidBitwiseOperatorsWithBooleans());
    registry.registerWarningRule(AvoidCollapsibleIf());
    registry.registerWarningRule(AvoidConditionsWithBooleanLiterals());
    registry.registerWarningRule(AvoidConstantAssertConditions());
    registry.registerWarningRule(AvoidContinue());
    registry.registerWarningRule(AvoidDefaultToString());
    registry.registerWarningRule(AvoidDuplicateConstantValues());
    registry.registerWarningRule(AvoidDuplicateExports());
    registry.registerWarningRule(AvoidDuplicateMapKeys());
    registry.registerWarningRule(AvoidEqualExpressions());
    registry.registerWarningRule(AvoidIdenticalExceptionHandlingBlocks());
    registry.registerWarningRule(AvoidLateFinalReassignment());
    registry.registerWarningRule(AvoidNestedTryStatements());
    registry.registerWarningRule(AvoidOneFieldRecords());
    registry.registerWarningRule(AvoidPositionalRecordFieldAccess());
    registry.registerWarningRule(AvoidPositionalRecordFields());
    registry.registerWarningRule(AvoidRecursiveToString());
    registry.registerWarningRule(AvoidRedundantAsync());
    registry.registerWarningRule(AvoidRedundantElse());
    registry.registerWarningRule(AvoidRedundantPositionalFieldName());
    registry.registerWarningRule(AvoidRepeatedPropertyAliases());
    registry.registerWarningRule(AvoidReturningVoid());
    registry.registerWarningRule(AvoidSelfAssignment());
    registry.registerWarningRule(AvoidSelfCompare());
    registry.registerWarningRule(AvoidStreamToString());
    registry.registerWarningRule(AvoidThrow());
    registry.registerWarningRule(AvoidUnassignedFields());
    registry.registerWarningRule(AvoidUnassignedLateFields());
    registry.registerWarningRule(AvoidUnnecessaryFutures());
    registry.registerWarningRule(AvoidUnnecessaryIf());
    registry.registerWarningRule(UseSetstateSynchronously());
    registry.registerWarningRule(UseThenAnswer());

    // Register fixes for rules
    registry.registerFixForRule(AlwaysRemoveListener.code, AlwaysRemoveListenerFix.new);
    registry.registerFixForRule(AvoidCascadeAfterIfNull.code, AvoidCascadeAfterIfNullFix.new);
    registry.registerFixForRule(DisposeFields.code, DisposeFieldsFix.new);
    registry.registerFixForRule(DisposeProvidedInstances.code, DisposeProvidedInstancesFix.new);
    registry.registerFixForRule(AvoidCommentedOutCode.code, AvoidCommentedOutCodeFix.new);
    registry.registerFixForRule(AvoidDuplicateCascades.code, AvoidDuplicateCascadesFix.new);
    registry.registerFixForRule(
      PreferAbstractFinalStaticClass.code,
      PreferAbstractFinalStaticClassFix.new,
    );
    registry.registerFixForRule(PreferCenterOverAlign.code, PreferCenterOverAlignFix.new);
    registry.registerFixForRule(PreferAlignOverContainer.code, ChangeWidgetNameFix.alignFix);
    registry.registerFixForRule(PreferExplicitFunctionType.code, PreferExplicitFunctionTypeFix.new);
    registry.registerFixForRule(PreferPaddingOverContainer.code, PreferPaddingOverContainerFix.new);
    registry.registerFixForRule(PreferAnyOrEvery.code, PreferAnyOrEveryFix.new);
    registry.registerFixForRule(PreferEnumsByName.code, PreferEnumsByNameFix.new);
    registry.registerFixForRule(PreferExpectLater.code, PreferExpectLaterFix.new);
    registry.registerFixForRule(PreferIterableOf.code, PreferIterableOfFix.new);
    registry.registerFixForRule(PreferReturnAwait.code, PreferReturnAwaitFix.new);
    registry.registerFixForRule(
      PreferSimplerPatternsNullCheck.code,
      PreferSimplerPatternsNullCheckFix.new,
    );
    registry.registerFixForRule(PreferWildcardPattern.code, PreferWildcardPatternFix.new);
    registry.registerFixForRule(
      AvoidUnnecessaryHookWidgets.code,
      AvoidUnnecessaryHookWidgetsFix.new,
    );
    registry.registerFixForRule(
      UseDedicatedMediaQueryMethods.code,
      UseDedicatedMediaQueryMethodsFix.new,
    );
    registry.registerFixForRule(UseNotifierSuffix.code, AddSuffixFix.notifierFix);
    registry.registerFixForRule(
      AvoidUnnecessaryConsumerWidgets.code,
      AvoidUnnecessaryConsumerWidgetsFix.new,
    );
    registry.registerFixForRule(AvoidGenericsShadowing.code, AvoidGenericsShadowingFix.new);
    registry.registerFixForRule(AvoidMapKeysContains.code, AvoidMapKeysContainsFix.new);
    registry.registerFixForRule(AvoidMountedCheckInFinally.code, AvoidMountedCheckInFinallyFix.new);
    registry.registerFixForRule(AvoidOnlyRethrow.code, AvoidOnlyRethrowFix.new);
    registry.registerFixForRule(AvoidThrowInCatchBlock.code, AvoidThrowInCatchBlockFix.new);
    registry.registerFixForRule(AvoidIncompleteCopyWith.code, AvoidIncompleteCopyWithFix.new);
    registry.registerFixForRule(AvoidIncorrectImageOpacity.code, AvoidIncorrectImageOpacityFix.new);
    registry.registerFixForRule(
      AvoidUnnecessaryGestureDetector.code,
      AvoidUnnecessaryGestureDetectorFix.new,
    );
    registry.registerFixForRule(AvoidUnnecessaryOverrides.code, AvoidUnnecessaryOverridesFix.new);
    registry.registerFixForRule(
      AvoidUnnecessaryOverridesInState.code,
      AvoidUnnecessaryOverridesInStateFix.new,
    );
    registry.registerFixForRule(AvoidUnnecessarySetstate.code, AvoidUnnecessarySetstateFix.new);
    registry.registerFixForRule(
      AvoidUnnecessaryStatefulWidgets.code,
      AvoidUnnecessaryStatefulWidgetsFix.new,
    );

    registry.registerFixForRule(ProperSuperCalls.code, ProperSuperCallsFix.new);
    registry.registerFixForRule(PreferClassDestructuring.code, PreferClassDestructuringFix.new);
    registry.registerFixForRule(UseClosestBuildContext.code, UseClosestBuildContextFix.new);
    registry.registerFixForRule(UseExistingDestructuring.code, UseExistingDestructuringFix.new);
    registry.registerFixForRule(UseExistingVariable.code, UseExistingVariableFix.new);
    registry.registerFixForRule(
      AvoidSingleFieldDestructuring.code,
      AvoidSingleFieldDestructuringFix.new,
    );
    registry.registerFixForRule(AvoidBorderAll.code, AvoidBorderAllFix.new);
    registry.registerFixForRule(AvoidExpandedAsSpacer.code, AvoidExpandedAsSpacerFix.new);
    registry.registerFixForRule(AvoidNotifierConstructors.code, AvoidNotifierConstructorsFix.new);
    registry.registerFixForRule(AvoidRefReadInsideBuild.code, AvoidRefReadInsideBuildFix.new);
    registry.registerFixForRule(AvoidStateConstructors.code, AvoidStateConstructorsFix.new);
    registry.registerFixForRule(PreferAsyncCallback.code, PreferAsyncCallbackFix.new);
    registry.registerFixForRule(
      PreferComputeOverIsolateRun.code,
      PreferComputeOverIsolateRunFix.new,
    );
    registry.registerFixForRule(PreferConstBorderRadius.code, PreferConstBorderRadiusFix.new);
    registry.registerFixForRule(
      PreferConstrainedBoxOverContainer.code,
      PreferConstrainedBoxOverContainerFix.new,
    );
    registry.registerFixForRule(AvoidWrappingInPadding.code, AvoidWrappingInPaddingFix.new);
    registry.registerFixForRule(PreferContainer.code, PreferContainerFix.new);
    registry.registerFixForRule(
      PreferCorrectEdgeInsetsConstructor.code,
      PreferCorrectEdgeInsetsConstructorFix.new,
    );
    registry.registerFixForRule(PreferForLoopInChildren.code, PreferForLoopInChildrenFix.new);
    registry.registerFixForRule(PreferSingleSetstate.code, PreferSingleSetstateFix.new);
    registry.registerFixForRule(PreferSizedBoxSquare.code, PreferSizedBoxSquareFix.new);
    registry.registerFixForRule(PreferTextRich.code, PreferTextRichFix.new);
    registry.registerFixForRule(
      PreferTransformOverContainer.code,
      ChangeWidgetNameFix.transformFix,
    );
    registry.registerFixForRule(PreferVoidCallback.code, PreferVoidCallbackFix.new);
    registry.registerFixForRule(
      UseRefAndStateSynchronously.code,
      UseRefAndStateSynchronouslyFix.new,
    );
    registry.registerFixForRule(UseRefReadSynchronously.code, UseRefReadSynchronouslyFix.new);
    registry.registerFixForRule(PreferUseCallback.code, PreferUseCallbackFix.new);
    registry.registerFixForRule(PreferUsePrefix.code, PreferUsePrefixFix.new);
    registry.registerFixForRule(UseSliverPrefix.code, UseSliverPrefixFix.new);
    // Register assists
    registry.registerAssist(ConvertIterableMapToCollectionFor.new);
  }
}
