import 'package:analysis_server_plugin/registry.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_any_version.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_declaring_call_method.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_dependency_overrides.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_initializers.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_mixins.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_named_imports.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_patterns.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_duplicate_switch_case_conditions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_explicit_pattern_field_name.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_importing_entrypoint_exports.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_incorrect_uri.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_keywords_in_wildcard_pattern.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_misused_set_literals.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_misused_wildcard_pattern.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nested_switch_expressions.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_nested_switches.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_non_null_assertion.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_parameter_aliases.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_single_child_column_or_row.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_slow_collection_methods.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unassigned_local_variable.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unconditional_break.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_block.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_continue.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_parentheses.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unnecessary_return.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unreachable_for_loop.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unsafe_collection_methods.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unsafe_reduce.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unused_assignment.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/avoid_unused_local_variable.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/consistent_update_render_object.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_correct_static_icon_provider.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_dedicated_media_query_methods.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_extracting_callbacks.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_number_format.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_providing_intl_description.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_providing_intl_examples.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_publish_to_none.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_sliver_prefix.dart';
import 'package:flutter_skill_lints/src/additional_lints/rules/prefer_type_over_var.dart';

/// Registers additional clean-room DCM-inspired lint rules.
void registerDcmExpansionLints(PluginRegistry registry) {
  registry.registerWarningRule(AvoidAnyVersion());
  registry.registerWarningRule(AvoidDeclaringCallMethod());
  registry.registerWarningRule(AvoidDependencyOverrides());
  registry.registerWarningRule(AvoidDuplicateInitializers());
  registry.registerWarningRule(AvoidDuplicateMixins());
  registry.registerWarningRule(AvoidDuplicateNamedImports());
  registry.registerWarningRule(AvoidDuplicatePatterns());
  registry.registerWarningRule(AvoidDuplicateSwitchCaseConditions());
  registry.registerWarningRule(AvoidExplicitPatternFieldName());
  registry.registerWarningRule(AvoidImportingEntrypointExports());
  registry.registerWarningRule(AvoidIncorrectUri());
  registry.registerWarningRule(AvoidKeywordsInWildcardPattern());
  registry.registerWarningRule(AvoidMisusedSetLiterals());
  registry.registerWarningRule(AvoidMisusedWildcardPattern());
  registry.registerWarningRule(AvoidNestedSwitchExpressions());
  registry.registerWarningRule(AvoidNestedSwitches());
  registry.registerWarningRule(AvoidNonNullAssertion());
  registry.registerWarningRule(AvoidParameterAliases());
  registry.registerWarningRule(AvoidSingleChildColumnOrRow());
  registry.registerWarningRule(AvoidSlowCollectionMethods());
  registry.registerWarningRule(AvoidUnassignedLocalVariable());
  registry.registerWarningRule(AvoidUnconditionalBreak());
  registry.registerWarningRule(AvoidUnnecessaryBlock());
  registry.registerWarningRule(AvoidUnnecessaryContinue());
  registry.registerWarningRule(AvoidUnnecessaryParentheses());
  registry.registerWarningRule(AvoidUnnecessaryReturn());
  registry.registerWarningRule(AvoidUnreachableForLoop());
  registry.registerWarningRule(AvoidUnsafeCollectionMethods());
  registry.registerWarningRule(AvoidUnsafeReduce());
  registry.registerWarningRule(AvoidUnusedAssignment());
  registry.registerWarningRule(AvoidUnusedLocalVariable());
  registry.registerWarningRule(ConsistentUpdateRenderObject());
  registry.registerWarningRule(PreferCorrectStaticIconProvider());
  registry.registerWarningRule(PreferDedicatedMediaQueryMethods());
  registry.registerWarningRule(PreferExtractingCallbacks());
  registry.registerWarningRule(PreferNumberFormat());
  registry.registerWarningRule(PreferProvidingIntlDescription());
  registry.registerWarningRule(PreferProvidingIntlExamples());
  registry.registerWarningRule(PreferPublishToNone());
  registry.registerWarningRule(PreferSliverPrefix());
  registry.registerWarningRule(PreferTypeOverVar());
}
