name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  ci:
    name: Full CI
    uses: ./.github/workflows/dart.yml

  publish:
    name: Publish to pub.dev
    needs: ci
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
